spring:
  application:
    name: rest-with-java
  datasource:
    spring.datasource.driver-class-name: com.mysql.cj.jdbc.driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java_meiguins?useTimezone=true&serverTimezone=UTC
    username: root
    password: Kk@068570
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

logging:
  level:
    root: WARN
    #br.com.meiguiigfns: DEBUG